### ISSUE TITLE
Rails 5 compatibility?

### ISSUE THREAD

**Issue by maia** [afair/postgresql_cursor#22]
With Rails 5 around the corner, no recent commits to this project and a few forks with a few small optimiztions that have not been pulled back in, I'd like to ask if a different way of lazily plucking attributes has arisen recently or if postgresql_cursor is still suggested to use?

Thanks!

**Comment by afair** [comment]
See #21 

In fact, you yourself opened that issue with this same question.

**Comment by maia** [comment]
@afair I don't know how I managed to forget having asked before, but I sincerely apologize!
