### ISSUE TITLE
Declaring cursors with NO SCROLL?

### ISSUE THREAD

**Issue by FooBarWidget** [afair/postgresql_cursor#31]
The `DECLARE` command allows the `NO SCROLL` argument, which hints to PostgreSQL that you will only be scrolling forward, not backwards. If you do not specify this argument then PostgreSQL tries to figure out for you whether it should allow scrolling or not, although the documentation does not explain what that means.

It seems this gem is only designed for scrolling forward anyway, so would it be a good idea to always call DECLARE with NO SCROLL as a micro-optimization? According to the documentation, NO SCROLL was introduced in PostgreSQL 8.3, which is *very* old. For reference: Ubuntu 12.04 and Debian 7 both supply PostgreSQL 9.1.

Documentation on cursors: https://www.postgresql.org/docs/9.6/static/plpgsql-cursors.html

**Comment by FooBarWidget** [comment]
I found [the documentation](https://www.postgresql.org/docs/9.1/static/sql-declare.html#SQL-DECLARE-NOTES) on what PostgreSQL does when neither `SCROLL` nor `NO SCROLL` is set:

> However, for compatibility with earlier versions, PostgreSQL will allow backward fetches without SCROLL, if the cursor's query plan is simple enough that no extra overhead is needed to support it.

**Comment by afair** [comment]
Agreed! I'll add that in.
