### ISSUE TITLE
Add configuration for own name of cursor

### ISSUE THREAD

**Issue by isqad** [afair/postgresql_cursor#38]
I'd like to assign my own name of cursor during declare. Here it is defined rigidly:
 
https://github.com/afair/postgresql_cursor/blob/410748762c4d97c93a8095070ea872a1e75739a1/lib/postgresql_cursor/cursor.rb#L180

**Comment by afair** [comment]
I added that capability in commit 3ba3253. Use the cursor_name: "myname" (which must be a valid cursor name. I am curious why you would need this? Perhaps tracing though the system.
