### ISSUE TITLE
each_instance doesn't handle enum attributes?

### ISSUE THREAD

**Issue by chickenburgers** [afair/postgresql_cursor#40]
First of all, great gem, love it 👍 

I've only run into a problem with enum attributes in ActiveRecord. If I define a model with an enum attribute, .each() outputs the symbolic enum value, but .each_instance() outputs the underlying numeric value. e.g.

class User < ApplicationRecord
    enum gender: [:male, :female]
end

User.all.each {|u| puts u.gender}                  # Outputs "male", "male", "female"
User.all.each_instance {|u| puts u.gender}   # Outputs 0, 0, 1

**Comment by afair** [comment]
Thanks, @chickenburgers (what a cool name!)

I looked on this again today. As far as I can tell, I'm doing the correct thing in instantiating the record. The enum's act as if they aren't defined. Could be an activerecord issue? Or there is a newer way to to it? Frustrating. 😢

**Comment by prashantvithani** [comment]
@afair I'm wondering why `column_types` is used in `each_instance` or `each_instance_batch` for activerecord version greater than 4 (5.2.3 to be precise). If I instantiate the object with `klass.send(:instantiate, row)` or simply `klass.instantiate(row)` (without `column_types`), it'd map the enum correctly while instantiating the AR object. Am I missing something here?
