### ISSUE TITLE
uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQLAdapter

### ISSUE THREAD

**Issue by mikebaldry** [afair/postgresql_cursor#41]
For anyone seeing this error, I encountered it when adding `postgresql_cursor` to my `Gemfile`.

I had to use `gem "postgresql_cursor", require: false` and then `require "postgresql_cursor"` manually where I needed it.

This would be good to document, I think.

Rails 4.2.11, Ruby 2.5.3p105, Bundler 1.17.2

**Comment by rstacruz** [comment]
If anyone else has encountered this, this has been fixed in v0.6.3. Upgrading would fix it.
