### ISSUE TITLE
AR#each_row doesn't accept options

### ISSUE THREAD

**Issue by RaVbaker** [afair/postgresql_cursor#6]
According to my tests and code - https://github.com/afair/postgresql_cursor/blob/master/lib/postgresql_cursor.rb#L161 - each_row is not using `options` provided in argument. But what's funny the each_instance is using them properly.

I will provide fix in PR soon.

**Comment by alegrria** [comment]
HI guys!
Thanks for the gem.
I'm trying to use it for processing pgSQL query results in chunks, but seems that each_row still doesn't accept options. 

`results.each_row(options={block_size:1000}) { |block| csv << block }`

![image](https://user-images.githubusercontent.com/1235819/32704776-1b92c03e-c80b-11e7-888a-08f74a52c943.png)

I appreciate any tips! 
TIA
